package optparam

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// BuilderOptions configures EmitGoBuilder.
type BuilderOptions struct {
	// Package is the package clause emitted at the top of the file.
	Package string
	// FuncName is the name of the generated builder function. The
	// params struct is named "<FuncName>Params".
	FuncName string
	// ParamsTypeName overrides the generated params struct name. If
	// empty, "<FuncName>Params" is used.
	ParamsTypeName string
	// Fragment omits package and import declarations. The returned
	// declarations are intended to be embedded in a larger generated
	// Go file that will be gofmt'd by the caller.
	Fragment bool
}

// EmitGoBuilder generates Go code that composes the SQL at runtime from
// the segment list. The returned source is gofmt'd.
//
// The generated function signature is:
//
//	func <FuncName>(p <FuncName>Params) (sql string, args map[string]interface{}, variant string)
//
// For every kind of segment the output SQL equals the variant
// EnumerateVariants would produce for the same call-site inputs.
func EmitGoBuilder(segments []Segment, params []Param, opts BuilderOptions) (string, error) {
	if opts.Package == "" && !opts.Fragment {
		return "", fmt.Errorf("BuilderOptions.Package is required")
	}
	if opts.FuncName == "" {
		return "", fmt.Errorf("BuilderOptions.FuncName is required")
	}
	paramsTypeName := opts.ParamsTypeName
	if paramsTypeName == "" {
		paramsTypeName = opts.FuncName + "Params"
	}
	byName := map[string]Param{}
	for _, p := range params {
		byName[p.Name] = p
	}

	// Collect all params that appear on a non-fixed segment plus required
	// bind params, in alphabetical order, so struct field layout is stable.
	fieldNames := paramsOnSegments(segments)
	fieldNames = append(fieldNames, requiredParams(params, fieldNames)...)
	sort.Strings(fieldNames)

	var b strings.Builder
	if !opts.Fragment {
		fmt.Fprintf(&b, "// Code generated by internal/optparam. DO NOT EDIT.\n\n")
		fmt.Fprintf(&b, "package %s\n\n", opts.Package)
		b.WriteString("import (\n")
		b.WriteString("\t\"sort\"\n")
		b.WriteString("\t\"strings\"\n")
		b.WriteString(")\n\n")
	}

	// Params struct.
	fmt.Fprintf(&b, "type %s struct {\n", paramsTypeName)
	for _, name := range fieldNames {
		p, ok := byName[name]
		if !ok {
			return "", fmt.Errorf("internal: segment param %q has no Param entry", name)
		}
		goType, err := goFieldType(p)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\t%s %s\n", exportIdent(name), goType)
	}
	// Plus the inline-rewritten null_is_null params: they are not
	// gated by any segment kind, but the caller still needs to pass
	// the nullable value.
	nullables := nullIsNullParams(params, segments)
	sort.Strings(nullables)
	for _, name := range nullables {
		p := byName[name]
		goType, err := goNullableType(p)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\t%s %s\n", exportIdent(name), goType)
	}
	b.WriteString("}\n\n")

	// Builder function.
	fmt.Fprintf(&b, "func %s(p %s) (sql string, args map[string]interface{}, variant string) {\n",
		opts.FuncName, paramsTypeName)
	b.WriteString("\tvar b strings.Builder\n")
	b.WriteString("\targs = map[string]interface{}{}\n")
	b.WriteString("\tvar parts []string\n\n")
	for _, seg := range segments {
		switch seg.Kind {
		case SegFixed:
			fmt.Fprintf(&b, "\tb.WriteString(%s)\n", strconv.Quote(seg.Text))
		case SegOmitWhenNull:
			field := exportIdent(seg.Param)
			fmt.Fprintf(&b, "\tif p.%s != nil {\n", field)
			fmt.Fprintf(&b, "\t\tb.WriteString(%s)\n", strconv.Quote(seg.Text))
			fmt.Fprintf(&b, "\t\targs[%s] = *p.%s\n", strconv.Quote(seg.Param), field)
			fmt.Fprintf(&b, "\t\tparts = append(parts, %s)\n", strconv.Quote(seg.Param))
			b.WriteString("\t}\n")
		case SegOmitWhenEmpty:
			field := exportIdent(seg.Param)
			fmt.Fprintf(&b, "\tif len(p.%s) > 0 {\n", field)
			fmt.Fprintf(&b, "\t\tb.WriteString(%s)\n", strconv.Quote(seg.Text))
			fmt.Fprintf(&b, "\t\targs[%s] = p.%s\n", strconv.Quote(seg.Param), field)
			fmt.Fprintf(&b, "\t\tparts = append(parts, %s)\n", strconv.Quote(seg.Param))
			b.WriteString("\t}\n")
		case SegOrderByChoice:
			emitOrderByChoice(&b, seg)
		}
	}
	required := requiredParams(params, nil)
	sort.Strings(required)
	for _, name := range required {
		field := exportIdent(name)
		fmt.Fprintf(&b, "\targs[%s] = p.%s\n", strconv.Quote(name), field)
	}
	// null_is_null: always-emit args entry from the nullable wrapper.
	for _, name := range nullables {
		field := exportIdent(name)
		fmt.Fprintf(&b, "\targs[%s] = p.%s\n", strconv.Quote(name), field)
	}
	b.WriteString("\n")
	b.WriteString("\tsort.Strings(parts)\n")
	b.WriteString("\tlabel := \"(none)\"\n")
	b.WriteString("\tif len(parts) > 0 {\n")
	b.WriteString("\t\tlabel = strings.Join(parts, \"+\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn b.String(), args, label\n")
	b.WriteString("}\n")

	if opts.Fragment {
		return b.String(), nil
	}
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt generated source: %w\n%s", err, b.String())
	}
	return string(formatted), nil
}

func emitOrderByChoice(b *strings.Builder, seg Segment) {
	field := exportIdent(seg.Param)
	fmt.Fprintf(b, "\t{\n")
	fmt.Fprintf(b, "\t\tchoice := p.%s\n", field)
	fmt.Fprintf(b, "\t\tif choice == \"\" {\n")
	fmt.Fprintf(b, "\t\t\tchoice = %s\n", strconv.Quote(seg.Default))
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t\tswitch choice {\n")
	keys := make([]string, 0, len(seg.Choices))
	for k := range seg.Choices {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "\t\tcase %s:\n", strconv.Quote(k))
		fmt.Fprintf(b, "\t\t\tb.WriteString(%s)\n", strconv.Quote(seg.Choices[k]))
	}
	fmt.Fprintf(b, "\t\tdefault:\n")
	fmt.Fprintf(b, "\t\t\tpanic(\"orderby %s: unknown choice \" + choice)\n", seg.Param)
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t\tparts = append(parts, %s+\"=\"+choice)\n", strconv.Quote(seg.Param))
	fmt.Fprintf(b, "\t}\n")
}

// paramsOnSegments lists param names referenced by omit/empty/orderby
// segments. These are the params surfaced through the builder struct.
func paramsOnSegments(segments []Segment) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range segments {
		if s.Kind == SegFixed || seen[s.Param] {
			continue
		}
		seen[s.Param] = true
		out = append(out, s.Param)
	}
	return out
}

// nullIsNullParams returns params that have mode null_is_null. They are
// always present at runtime (no gating) but still need a struct field so
// the caller can pass the value.
func nullIsNullParams(params []Param, segments []Segment) []string {
	// Mode is on the Param, segments lost the marker kind for SegFixed.
	// Cross-reference: any Param with ModeNullIsNull contributes.
	var out []string
	for _, p := range params {
		if p.Mode == ModeNullIsNull {
			out = append(out, p.Name)
		}
	}
	_ = segments
	return out
}

// goFieldType maps a segment-gated Param to its struct field type.
func goFieldType(p Param) (string, error) {
	switch p.Mode {
	case ModeRequired:
		return goRequiredType(p)
	case ModeOmitWhenNull:
		return goPointerType(p)
	case ModeOmitWhenEmpty:
		return goSliceType(p)
	case ModeOrderByChoice:
		return "string", nil
	default:
		return "", fmt.Errorf("param %q: mode %s not supported on a segment", p.Name, p.Mode)
	}
}

func goRequiredType(p Param) (string, error) {
	upper := strings.ToUpper(strings.TrimSpace(p.Type))
	if strings.HasPrefix(upper, "ARRAY<") && strings.HasSuffix(upper, ">") {
		return goSliceType(p)
	}
	switch upper {
	case "STRING":
		return "string", nil
	case "INT64":
		return "int64", nil
	case "BOOL":
		return "bool", nil
	case "FLOAT64":
		return "float64", nil
	case "BYTES":
		return "[]byte", nil
	default:
		return "", fmt.Errorf("param %q: no Go type mapping for Spanner type %q", p.Name, p.Type)
	}
}

func goPointerType(p Param) (string, error) {
	switch strings.ToUpper(strings.TrimSpace(p.Type)) {
	case "STRING":
		return "*string", nil
	case "INT64":
		return "*int64", nil
	case "BOOL":
		return "*bool", nil
	case "FLOAT64":
		return "*float64", nil
	case "BYTES":
		return "*[]byte", nil
	default:
		return "", fmt.Errorf("param %q: no *T mapping for Spanner type %q", p.Name, p.Type)
	}
}

func requiredParams(params []Param, existing []string) []string {
	seen := map[string]bool{}
	for _, name := range existing {
		seen[name] = true
	}
	var out []string
	for _, p := range params {
		if p.Mode != ModeRequired || seen[p.Name] {
			continue
		}
		out = append(out, p.Name)
		seen[p.Name] = true
	}
	return out
}

func goSliceType(p Param) (string, error) {
	// Type is expected to look like ARRAY<STRING>.
	upper := strings.ToUpper(strings.TrimSpace(p.Type))
	if !strings.HasPrefix(upper, "ARRAY<") || !strings.HasSuffix(upper, ">") {
		return "", fmt.Errorf("param %q: omit_when_empty requires ARRAY<...> Spanner type, got %q", p.Name, p.Type)
	}
	elem := strings.TrimSuffix(strings.TrimPrefix(upper, "ARRAY<"), ">")
	switch elem {
	case "STRING":
		return "[]string", nil
	case "INT64":
		return "[]int64", nil
	case "BOOL":
		return "[]bool", nil
	case "FLOAT64":
		return "[]float64", nil
	default:
		return "", fmt.Errorf("param %q: no []T mapping for element %q", p.Name, elem)
	}
}

// goNullableType emits a Spanner-style nullable wrapper for null_is_null.
// For the PoC we use the cloud.google.com/go/spanner Null* types only by
// name; the caller's module is expected to import them.
func goNullableType(p Param) (string, error) {
	switch strings.ToUpper(strings.TrimSpace(p.Type)) {
	case "STRING":
		return "spanner.NullString", nil
	case "INT64":
		return "spanner.NullInt64", nil
	case "BOOL":
		return "spanner.NullBool", nil
	case "FLOAT64":
		return "spanner.NullFloat64", nil
	default:
		return "", fmt.Errorf("param %q: no nullable wrapper for Spanner type %q", p.Name, p.Type)
	}
}

// exportIdent capitalizes the leading letter and converts snake_case to
// CamelCase for use as a Go struct field name.
func exportIdent(name string) string {
	var b strings.Builder
	upper := true
	for _, r := range name {
		if r == '_' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(toUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - ('a' - 'A')
	}
	return r
}

// VerifyBuilderRoundTrip asserts every verified variant can be
// reproduced byte-for-byte by composing segments with that variant's
// presence and choice sets. Callers should invoke this at codegen time
// before writing the generated builder file.
func VerifyBuilderRoundTrip(segments []Segment, variants []Variant) error {
	for _, v := range variants {
		present := map[string]bool{}
		for _, name := range v.PresentParams {
			present[name] = true
		}
		composed := ComposeVariant(segments, Presence{Present: present, Choices: v.ChoiceAssignments})
		if composed != v.SQL {
			return fmt.Errorf("variant %s round-trip mismatch:\n  composed: %q\n  variant:  %q",
				v.Key(), composed, v.SQL)
		}
	}
	return nil
}
