package main

// googleSQLSurfaceQueries records documented generic GoogleSQL grammar
// surfaces whose accepted PLAN shapes or explicit runtime capability errors
// are useful to retain independently of GQL coverage.
var googleSQLSurfaceQueries = []queryCase{
	{Label: "google-sql-surface/accepted/having", SQL: `SELECT SingerId, COUNT(*) AS album_count FROM Albums GROUP BY SingerId HAVING COUNT(*) > 1`},
	{Label: "google-sql-surface/accepted/select-all", SQL: `SELECT ALL SingerId FROM Albums`},
	{Label: "google-sql-surface/accepted/star-except", SQL: `SELECT s.* EXCEPT (LastName), "x" AS tag FROM Singers AS s`},
	{Label: "google-sql-surface/accepted/star-replace", SQL: `SELECT * REPLACE (UPPER(FirstName) AS FirstName) FROM Singers`},
	{Label: "google-sql-surface/accepted/select-as-value-subquery", SQL: `SELECT value_column FROM (SELECT AS VALUE SingerId FROM Singers) AS value_column`},
	{Label: "google-sql-surface/accepted/for-update-read-write", SQL: `SELECT SingerId, FirstName FROM Singers WHERE SingerId > 0 FOR UPDATE`, PlanMode: planModeReadWrite},
	{Label: "google-sql-surface/accepted/aggregate-having-max", SQL: `SELECT SingerId, ANY_VALUE(AlbumTitle HAVING MAX AlbumId) AS latest_title FROM Albums GROUP BY SingerId`},
	{Label: "google-sql-surface/accepted/aggregate-having-min", SQL: `SELECT SingerId, ANY_VALUE(AlbumTitle HAVING MIN AlbumId) AS earliest_title FROM Albums GROUP BY SingerId`},
	{Label: "google-sql-surface/accepted/array-agg-order-limit", SQL: `SELECT SingerId, ARRAY_AGG(AlbumTitle ORDER BY AlbumId DESC LIMIT 2) AS titles FROM Albums GROUP BY SingerId`},
	{Label: "google-sql-surface/accepted/array-transform-lambda", SQL: `SELECT ARRAY_TRANSFORM([1, 2, 3], e -> e * 2) AS values`},
	{Label: "google-sql-surface/accepted/array-filter-lambda", SQL: `SELECT ARRAY_FILTER([1, 2, 3], e -> e != 2) AS values`},
	{Label: "google-sql-surface/accepted/in-unnest", SQL: `SELECT SingerId FROM Singers WHERE SingerId IN UNNEST([1, 2, 3])`},
	{Label: "google-sql-surface/accepted/with-expression", SQL: `SELECT SingerId, WITH(a AS COALESCE(FirstName, ''), b AS UPPER(a), LENGTH(b)) AS normalized_length FROM Singers`},
	{Label: "google-sql-surface/accepted/order-by-collate", SQL: `SELECT FirstName FROM Singers ORDER BY FirstName COLLATE "und:ci"`},
	{Label: "google-sql-surface/accepted/aggregate-count-distinct", SQL: `SELECT SingerId, COUNT(DISTINCT AlbumTitle) AS distinct_titles FROM Albums GROUP BY SingerId`},
	{Label: "google-sql-surface/accepted/aggregate-array-distinct-ignore-nulls", SQL: `SELECT SingerId, ARRAY_AGG(DISTINCT AlbumTitle IGNORE NULLS ORDER BY AlbumTitle) AS titles FROM Albums GROUP BY SingerId`},
	{Label: "google-sql-surface/accepted/aggregate-array-distinct-respect-nulls", SQL: `SELECT SingerId, ARRAY_AGG(DISTINCT AlbumTitle RESPECT NULLS ORDER BY AlbumTitle) AS titles FROM Albums GROUP BY SingerId`},
	{Label: "google-sql-surface/accepted/is-not-distinct-from", SQL: `SELECT NULL IS NOT DISTINCT FROM NULL AS not_distinct`},
	{Label: "google-sql-surface/accepted/is-distinct-from", SQL: `SELECT NULL IS DISTINCT FROM NULL AS distinct_value`},
	{Label: "google-sql-surface/accepted/correlated-unnest-explicit", SQL: `SELECT c.VenueId, price FROM Concerts AS c CROSS JOIN UNNEST(c.TicketPrices) AS price`},
	{Label: "google-sql-surface/accepted/correlated-unnest-implicit", SQL: `SELECT c.VenueId, price FROM Concerts AS c, c.TicketPrices AS price`},
	{Label: "google-sql-surface/accepted/correlated-unnest-left", SQL: `SELECT c.VenueId, price FROM Concerts AS c LEFT JOIN UNNEST(c.TicketPrices) AS price ON TRUE`},
	{Label: "google-sql-surface/accepted/in-subquery-control", SQL: `SELECT SingerId FROM Singers WHERE SingerId IN (SELECT SingerId FROM Albums)`},
	{Label: "google-sql-surface/accepted/in-unnest-array-subquery", SQL: `SELECT SingerId FROM Singers WHERE SingerId IN UNNEST(ARRAY(SELECT SingerId FROM Albums))`},
	{Label: "google-sql-surface/accepted/not-in-subquery-control", SQL: `SELECT SingerId FROM Singers WHERE SingerId NOT IN (SELECT SingerId FROM Albums)`},
	{Label: "google-sql-surface/accepted/not-in-unnest-array-subquery", SQL: `SELECT SingerId FROM Singers WHERE SingerId NOT IN UNNEST(ARRAY(SELECT SingerId FROM Albums))`},
	{Label: "google-sql-surface/accepted/group-by-ordinal", SQL: `SELECT SingerId, COUNT(*) AS album_count FROM Albums GROUP BY 1`},
	{Label: "google-sql-surface/accepted/group-by-name-control", SQL: `SELECT SingerId, COUNT(*) AS album_count FROM Albums GROUP BY SingerId`},
	{Label: "google-sql-surface/accepted/tablesample-subquery", SQL: `SELECT SingerId FROM (SELECT SingerId FROM Singers WHERE SingerId > 0) TABLESAMPLE BERNOULLI (50 PERCENT)`},
	{Label: "google-sql-surface/accepted/tablesample-join", SQL: `SELECT s.SingerId, a.AlbumId FROM Singers AS s TABLESAMPLE RESERVOIR (2 ROWS) JOIN Albums AS a ON a.SingerId = s.SingerId`},
	{Label: "google-sql-surface/accepted/struct-expression-star", SQL: `SELECT row_value.* FROM (SELECT STRUCT(1 AS x, "a" AS y) AS row_value)`},
	{Label: "google-sql-surface/accepted/unnest-array-of-struct", SQL: `SELECT * FROM UNNEST(ARRAY<STRUCT<x INT64, y STRING>>[(1, "a"), (2, "b")])`},
	{Label: "google-sql-surface/accepted/set-operation-regular-first-value-second", SQL: `SELECT SingerId FROM Singers UNION ALL SELECT AS VALUE SingerId FROM Albums`},
	{Label: "google-sql-surface/accepted/set-operation-value-first-nested", SQL: `SELECT value_column FROM (SELECT AS VALUE SingerId FROM Singers UNION ALL SELECT SingerId FROM Albums) AS value_column`},

	{Label: "google-sql-surface/unsupported/core-pipe", SQL: `SELECT SingerId, FirstName FROM Singers |> WHERE SingerId > 0 |> SELECT SingerId |> ORDER BY SingerId |> LIMIT 2`},
	{Label: "google-sql-surface/unsupported/grouping-sets", SQL: `SELECT SingerId, SongGenre, COUNT(*) AS c FROM Songs GROUP BY GROUPING SETS ((SingerId), (SongGenre), ())`},
	{Label: "google-sql-surface/unsupported/rollup", SQL: `SELECT SingerId, SongGenre, COUNT(*) AS c FROM Songs GROUP BY ROLLUP(SingerId, SongGenre)`},
	{Label: "google-sql-surface/unsupported/cube", SQL: `SELECT SingerId, SongGenre, COUNT(*) AS c FROM Songs GROUP BY CUBE(SingerId, SongGenre)`},
	{Label: "google-sql-surface/unsupported/pivot", SQL: `SELECT * FROM (SELECT SingerId, SongGenre FROM Songs) PIVOT(COUNT(*) FOR SongGenre IN ("ROCK" AS rock, "JAZZ" AS jazz))`},
	{Label: "google-sql-surface/unsupported/unpivot", SQL: `SELECT SingerId, name_kind, name_value FROM Singers UNPIVOT(name_value FOR name_kind IN (FirstName, LastName))`},
	{Label: "google-sql-surface/unsupported/for-update-read-only", SQL: `SELECT SingerId, FirstName FROM Singers WHERE SingerId > 0 FOR UPDATE`, PlanMode: planModeReadOnly},
	{Label: "google-sql-surface/unsupported/lock-hint-with-for-update", SQL: `@{LOCK_SCANNED_RANGES=exclusive} SELECT MarketingBudget FROM Albums WHERE SingerId = 1 AND AlbumId = 1 FOR UPDATE`, PlanMode: planModeReadWrite},
	{Label: "google-sql-surface/unsupported/with-recursive", SQL: `WITH RECURSIVE nums AS (SELECT 1 AS n UNION ALL SELECT n + 1 FROM nums WHERE n < 3) SELECT n FROM nums`},
	{Label: "google-sql-surface/unsupported/select-as-value-top-level", SQL: `SELECT AS VALUE SingerId FROM Singers`},
	{Label: "google-sql-surface/unsupported/with-in-subquery", SQL: `SELECT * FROM (WITH x AS (SELECT SingerId FROM Singers) SELECT * FROM x)`},
	{Label: "google-sql-surface/unsupported/analytic-row-number", SQL: `SELECT SingerId, ROW_NUMBER() OVER (PARTITION BY LastName ORDER BY FirstName, SingerId) AS rn FROM Singers`},
	{Label: "google-sql-surface/unsupported/analytic-framed-sum", SQL: `SELECT SingerId, AlbumId, SUM(MarketingBudget) OVER (PARTITION BY SingerId ORDER BY AlbumId ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_budget FROM Albums`},
	{Label: "google-sql-surface/unsupported/tablesample-repeatable", SQL: `SELECT SingerId FROM Singers TABLESAMPLE BERNOULLI (10 PERCENT) REPEATABLE (42)`},
	{Label: "google-sql-surface/unsupported/select-as-struct-top-level", SQL: `SELECT AS STRUCT SingerId, FirstName FROM Singers`},
	{Label: "google-sql-surface/unsupported/lateral-cross", SQL: `SELECT s.SingerId, a.AlbumId FROM Singers AS s CROSS JOIN LATERAL (SELECT AlbumId FROM Albums WHERE Albums.SingerId = s.SingerId) AS a`},
	{Label: "google-sql-surface/unsupported/lateral-left", SQL: `SELECT s.SingerId, a.AlbumId FROM Singers AS s LEFT JOIN LATERAL (SELECT AlbumId FROM Albums WHERE Albums.SingerId = s.SingerId) AS a ON TRUE`},
	{Label: "google-sql-surface/unsupported/set-operation-by-name", SQL: `SELECT SingerId AS id, FirstName AS name FROM Singers UNION ALL BY NAME SELECT AlbumId AS id, AlbumTitle AS name FROM Albums`},
	{Label: "google-sql-surface/unsupported/set-operation-corresponding", SQL: `SELECT SingerId AS id, FirstName AS name FROM Singers UNION ALL CORRESPONDING SELECT AlbumId AS id, AlbumTitle AS name FROM Albums`},
	{Label: "google-sql-surface/unsupported/group-by-all", SQL: `SELECT SingerId, COUNT(*) AS album_count FROM Albums GROUP BY ALL`},
	{Label: "google-sql-surface/unsupported/match-recognize", SQL: `SELECT * FROM Albums MATCH_RECOGNIZE (PARTITION BY SingerId ORDER BY AlbumId MEASURES MATCH_NUMBER() AS match_num PATTERN (A) DEFINE A AS TRUE)`},
	{Label: "google-sql-surface/unsupported/set-operation-value-first-top-level", SQL: `SELECT AS VALUE SingerId FROM Singers UNION ALL SELECT SingerId FROM Albums`},
	{Label: "google-sql-surface/unsupported/secure-context", SQL: `SELECT SECURE_CONTEXT("key") AS value`},
}
