package main

// gqlSurfaceQueries retains broad GQL and SQL/GQL bridge acceptance coverage,
// including clauses that optimize to the same physical shape as a simpler
// control. Distinctive plan-shape claims live in the companion planvocab
// manifest; expected errors record runtime capability boundaries separately.
var gqlSurfaceQueries = append([]queryCase{
	{Label: "gql-surface/graph-table/baseline", SQL: `SELECT SingerId FROM GRAPH_TABLE(MusicGraph MATCH (p:Singers) RETURN p.SingerId AS SingerId)`},
	{Label: "gql-surface/graph-table/self-join-eliminated-control", SQL: `SELECT g.SingerId, s.FirstName FROM GRAPH_TABLE(MusicGraph MATCH (p:Singers) RETURN p.SingerId AS SingerId) AS g JOIN Singers AS s USING (SingerId)`},
	{Label: "gql-surface/graph-table/filter", SQL: `SELECT SingerId FROM GRAPH_TABLE(MusicGraph MATCH (p:Singers) RETURN p.SingerId AS SingerId) AS g WHERE SingerId > 0`},
	{Label: "gql-surface/graph-table/element-property", SQL: `SELECT n.FirstName AS first_name, n.SingerId AS singer_id FROM GRAPH_TABLE(MusicGraph MATCH (n:Singers) RETURN n)`},
	{Label: "gql-surface/graph-table/element-safe-to-json", SQL: `SELECT SAFE_TO_JSON(n) AS json_node FROM GRAPH_TABLE(MusicGraph MATCH (n:Singers) RETURN n)`},
	{Label: "gql-surface/linear/filter", SQL: `GRAPH MusicGraph MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId`},
	{Label: "gql-surface/linear/filter-where", SQL: `GRAPH MusicGraph MATCH (p:Singers) FILTER WHERE p.SingerId > 0 RETURN p.SingerId`},
	{Label: "gql-surface/linear/let", SQL: `GRAPH MusicGraph MATCH (p:Singers) LET next_id = p.SingerId + 1 RETURN p.SingerId, next_id`},
	{Label: "gql-surface/linear/for-with-offset", SQL: `GRAPH MusicGraph MATCH (p:Singers) FOR element IN [1, 2] WITH OFFSET AS off RETURN p.SingerId, element, off`},
	{Label: "gql-surface/linear/for-correlated", SQL: `GRAPH MusicGraph MATCH (p:Singers) FOR element IN GENERATE_ARRAY(1, p.SingerId) RETURN p.SingerId, element`},
	{Label: "gql-surface/call/correlated", SQL: `GRAPH MusicGraph MATCH (p:Singers) CALL (p) { MATCH (p)-[:CollabWith]->(q:Singers) RETURN q.SingerId AS friend_id } RETURN p.SingerId, friend_id`},
	{Label: "gql-surface/call/optional-correlated", SQL: `GRAPH MusicGraph MATCH (p:Singers) OPTIONAL CALL (p) { MATCH (p)-[:CollabWith]->(q:Singers) RETURN q.SingerId AS friend_id } RETURN p.SingerId, friend_id`},
	{Label: "gql-surface/call/uncorrelated-aggregate", SQL: `GRAPH MusicGraph MATCH (s:Singers) CALL () { MATCH (x:Singers)-[:CollabWith]->(y:Singers) RETURN COUNT(*) AS edge_count } RETURN s.SingerId AS singer_id, edge_count`},
	{Label: "gql-surface/subquery/correlated-exists", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, EXISTS { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f } AS has_friend`},
	{Label: "gql-surface/subquery/correlated-value", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, VALUE { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f.SingerId ORDER BY f.SingerId LIMIT 1 } AS first_friend_id`},
	{Label: "gql-surface/subquery/correlated-array", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, ARRAY { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f.SingerId } AS friend_ids`},
	{Label: "gql-surface/subquery/correlated-in", SQL: `GRAPH MusicGraph MATCH (s:Singers) FILTER s.SingerId IN { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f.SingerId } RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/subquery/correlated-not-in", SQL: `GRAPH MusicGraph MATCH (s:Singers) FILTER s.SingerId NOT IN { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f.SingerId } RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/subquery/exists-match-body", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, EXISTS { MATCH (x:Singers)-[:CollabWith]->(:Singers) FILTER x = s } AS has_friend`},
	{Label: "gql-surface/subquery/exists-pattern-body", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, EXISTS { (x:Singers WHERE x = s)-[:CollabWith]->(:Singers) } AS has_friend`},
	{Label: "gql-surface/subquery/exists-pattern-filter", SQL: `GRAPH MusicGraph MATCH (s:Singers) FILTER EXISTS { (x:Singers WHERE x = s)-[:CollabWith]->(f:Singers) } RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/subquery/exists-full-filter-control", SQL: `GRAPH MusicGraph MATCH (s:Singers) FILTER EXISTS { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f } RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/bridge/dml-update-recursive-in", SQL: `UPDATE Singers SET FirstName = FirstName WHERE SingerId IN { GRAPH MusicGraph MATCH (a:Singers WHERE a.SingerId = 1)-[:CollabWith]->{1,2}(b:Singers) RETURN b.SingerId }`, PlanMode: planModeReadWrite},
	{Label: "gql-surface/linear/next", SQL: `GRAPH MusicGraph MATCH (p:Singers) RETURN p NEXT RETURN p.SingerId`},
	{Label: "gql-surface/return/with-distinct-node-control", SQL: `GRAPH MusicGraph MATCH (p:Singers) WITH DISTINCT p RETURN p.SingerId`},
	{Label: "gql-surface/return/distinct-traversal", SQL: `GRAPH MusicGraph MATCH (p:Singers)-[:CollabWith]->(q:Singers) RETURN DISTINCT q.SingerId`},

	{Label: "gql-surface/set-operation/union-all-nontrivial", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id UNION ALL MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-surface/set-operation/union-distinct-nontrivial", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id UNION DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-surface/set-operation/intersect-distinct-nontrivial", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id INTERSECT DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-surface/set-operation/except-distinct-nontrivial", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id EXCEPT DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-surface/set-operation/intersect-all-nontrivial", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id INTERSECT ALL MATCH (c:Singers)-[:CollabWith]->(d:Singers) RETURN c.SingerId AS id`},
	{Label: "gql-surface/set-operation/except-all-nontrivial", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id EXCEPT ALL MATCH (c:Singers)-[:CollabWith]->(d:Singers) RETURN c.SingerId AS id`},
	{Label: "gql-surface/set-operation/reordered-intersect-distinct", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id INTERSECT DISTINCT MATCH (c:Singers)-[:CollabWith]->(d:Singers) RETURN d.SingerId AS dst_id, c.SingerId AS src_id`},
	{Label: "gql-surface/set-operation/three-arm-union-all", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id UNION ALL MATCH (c:Singers)-[:CollabWith]->(d:Singers) RETURN d.SingerId AS dst_id, c.SingerId AS src_id UNION ALL MATCH (e:Singers)-[:CollabWith]->(f:Singers) RETURN e.SingerId AS src_id, f.SingerId AS dst_id`},
	// FULL name alignment is accepted by the pinned Omni runtime even though the
	// normal GQL set-operation documentation does not advertise this spelling.
	{Label: "gql-surface/set-operation/full-union-all-omni", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS id FULL UNION ALL MATCH (t:Singers) RETURN t.SingerId AS id`},

	{Label: "gql-surface/search/any-single-hop", SQL: `GRAPH MusicGraph MATCH ANY (a:Singers)-[:CollabWith]->(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/search/any-shortest-bounded", SQL: `GRAPH MusicGraph MATCH ANY SHORTEST (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/search/any-shortest-trail-subpath", SQL: `GRAPH MusicGraph MATCH ANY SHORTEST (TRAIL (a:Singers)-[:CollabWith]->{1,3}(b:Singers)) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/search/all-single-hop-control", SQL: `GRAPH MusicGraph MATCH ALL (a:Singers)-[:CollabWith]->(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/mode/walk-fixed", SQL: `GRAPH MusicGraph MATCH WALK (a:Singers)-[:CollabWith]->(b:Singers)-[:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-surface/mode/acyclic-fixed", SQL: `GRAPH MusicGraph MATCH ACYCLIC (a:Singers)-[:CollabWith]->(b:Singers)-[:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-surface/mode/trail-fixed", SQL: `GRAPH MusicGraph MATCH TRAIL (a:Singers)-[:CollabWith]->(b:Singers)-[:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-surface/search/any-cheapest-bounded", SQL: `GRAPH MusicGraph MATCH ANY CHEAPEST (a:Singers)-[e:CollabWith COST 1]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/search/any-cheapest-property-cost", SQL: `GRAPH MusicGraph MATCH ANY CHEAPEST (a:Singers)-[e:CollabWith COST ABS(e.SingerId) + 1]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/search/any-bounded", SQL: `GRAPH MusicGraph MATCH ANY (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/search/all-bounded", SQL: `GRAPH MusicGraph MATCH ALL (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/mode/acyclic-quantified", SQL: `GRAPH MusicGraph MATCH ACYCLIC PATH (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/mode/trail-quantified", SQL: `GRAPH MusicGraph MATCH TRAIL PATH (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/mode/walk-quantified", SQL: `GRAPH MusicGraph MATCH WALK PATH (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/path/functions", SQL: `GRAPH MusicGraph MATCH p = (a:Singers)-[e:CollabWith]->(b:Singers) RETURN a.SingerId AS src_id, PATH_LENGTH(p) AS path_len, IS_ACYCLIC(p) AS acyclic, IS_TRAIL(p) AS trail`},
	{Label: "gql-surface/path/recursive-materialization", SQL: `GRAPH MusicGraph MATCH p = (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) LET ns = NODES(p), es = EDGES(p), first_node = PATH_FIRST(p), last_node = PATH_LAST(p) RETURN ARRAY_LENGTH(ns) AS node_count, ARRAY_LENGTH(es) AS edge_count, first_node.SingerId AS first_id, last_node.SingerId AS last_id, IS_SIMPLE(p) AS is_simple`},
	{Label: "gql-surface/path/construct", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e1:CollabWith]->(b:Singers)-[e2:CollabWith]->(c:Singers) LET constructed = PATH(a, e1, b, e2, c) RETURN PATH_LENGTH(constructed) AS path_length, ARRAY_LENGTH(NODES(constructed)) AS node_count, ARRAY_LENGTH(EDGES(constructed)) AS edge_count`},
	{Label: "gql-surface/path/concatenate", SQL: `GRAPH MusicGraph MATCH p = (a:Singers)-[e1:CollabWith]->(b:Singers), q = (b)-[e2:CollabWith]->(c:Singers) LET concatenated = p || q RETURN PATH_LENGTH(concatenated) AS path_length, ARRAY_LENGTH(NODES(concatenated)) AS node_count, ARRAY_LENGTH(EDGES(concatenated)) AS edge_count`},
	{Label: "gql-surface/path/quantified-subpath-where", SQL: `GRAPH MusicGraph MATCH (src:Singers) ((a:Singers)-[:CollabWith]->(b:Singers) WHERE a != b){1,2} -[:CollabWith]->(dst:Singers) RETURN src.SingerId AS src_id, dst.SingerId AS dst_id`},
	{Label: "gql-surface/path/zero-hop", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->{0,3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/path/two-quantified-segments", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->{1,2}(b:Singers)-[:CollabWith]->{1,2}(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-surface/element/functions", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[e:CollabWith]->(f:Singers) RETURN s.SingerId AS singer_id, ELEMENT_ID(s) AS singer_element_id, ELEMENT_DEFINITION_NAME(s) AS singer_definition, LABELS(s) AS singer_labels, PROPERTY_NAMES(s) AS singer_properties, ELEMENT_ID(e) AS edge_element_id, SOURCE_NODE_ID(e) AS source_node_id, DESTINATION_NODE_ID(e) AS destination_node_id`},
	{Label: "gql-surface/element/predicates", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e1:CollabWith]->(b:Singers)-[e2:CollabWith]->(c:Singers) FILTER ALL_DIFFERENT(e1, e2) AND NOT SAME(a, c) AND a IS SOURCE OF e1 AND b IS DESTINATION OF e1 AND a IS LABELED Singers AND PROPERTY_EXISTS(a, FirstName) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-surface/direction/any", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]-(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id, e.AlbumTitle AS album_title`},
	{Label: "gql-surface/direction/reverse", SQL: `GRAPH MusicGraph MATCH (a:Singers)<-[e:CollabWith]-(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id, e.AlbumTitle AS album_title`},
	{Label: "gql-surface/direction/source-predicate", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]-(b:Singers) FILTER a IS SOURCE OF e RETURN a.SingerId AS endpoint_id, b.SingerId AS other_id`},
	{Label: "gql-surface/direction/destination-predicate", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]-(b:Singers) FILTER a IS DESTINATION OF e RETURN a.SingerId AS endpoint_id, b.SingerId AS other_id`},
	{Label: "gql-surface/match/where", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->(b:Singers) WHERE a.SingerId != b.SingerId AND e.SingerId > 0 RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/match/element-where", SQL: `GRAPH MusicGraph MATCH (a:Singers WHERE a.SingerId > 0)-[e:CollabWith WHERE e.SingerId > 0]->(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/pattern/edge-only", SQL: `GRAPH MusicGraph MATCH -[e:CollabWith]-> RETURN e.SingerId AS src_id, e.FeaturingSingerId AS dst_id`},
	{Label: "gql-surface/pattern/wildcard-metadata", SQL: `GRAPH MusicGraph MATCH (n:%) RETURN n.SingerId AS singer_id, LABELS(n) AS labels, PROPERTY_NAMES(n) AS property_names, ELEMENT_DEFINITION_NAME(n) AS definition_name, ELEMENT_ID(n) AS element_id`},
	{Label: "gql-surface/pattern/negated-label", SQL: `GRAPH MusicGraph MATCH (n:!Singers) RETURN ELEMENT_ID(n) AS element_id`},
	{Label: "gql-surface/pattern/label-or", SQL: `GRAPH LabelGraph MATCH (n:(Singer|Album)) RETURN ELEMENT_ID(n) AS element_id`},
	{Label: "gql-surface/pattern/label-and", SQL: `GRAPH LabelGraph MATCH (n:(Singer&Person)) RETURN ELEMENT_ID(n) AS element_id`},
	{Label: "gql-surface/pattern/label-and-single-control", SQL: `GRAPH LabelGraph MATCH (n:Singer) RETURN ELEMENT_ID(n) AS element_id`},
	{Label: "gql-surface/pagination/skip", SQL: `GRAPH MusicGraph MATCH (p:Singers) SKIP 1 RETURN p.SingerId`},
	{Label: "gql-surface/pagination/offset", SQL: `GRAPH MusicGraph MATCH (p:Singers) OFFSET 1 RETURN p.SingerId`},
	{Label: "gql-surface/pagination/order-by-limit", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[:CollabWith]->(f:Singers) RETURN s.SingerId AS singer_id, f.SingerId AS friend_id ORDER BY friend_id DESC LIMIT 3`},
	{Label: "gql-surface/pagination/primitive-order-by-limit", SQL: `GRAPH MusicGraph MATCH (s:Singers) ORDER BY s.SingerId DESC LIMIT 3 RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/pagination/primitive-order-by-collate-limit", SQL: `GRAPH MusicGraph MATCH (s:Singers) ORDER BY s.FirstName COLLATE "und:ci", s.SingerId LIMIT 3 RETURN s.SingerId AS singer_id, s.FirstName AS first_name`},
	{Label: "gql-surface/with/group-order-limit", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[:CollabWith]->(f:Singers) WITH s.SingerId AS singer_id, COUNT(*) AS friend_count GROUP BY singer_id RETURN singer_id, friend_count ORDER BY friend_count DESC LIMIT 3`},
	{Label: "gql-surface/with/group-filter", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[:CollabWith]->(f:Singers) WITH s.SingerId AS singer_id, COUNT(*) AS friend_count GROUP BY singer_id FILTER friend_count > 0 RETURN singer_id, friend_count`},
	{Label: "gql-surface/with/implicit-grouping", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[:CollabWith]->(f:Singers) WITH s.SingerId AS singer_id, COUNT(*) AS friend_count RETURN singer_id, friend_count`},
	{Label: "gql-surface/graph-table/tablesample-bernoulli", SQL: `SELECT SingerId FROM GRAPH_TABLE(MusicGraph MATCH (s:Singers) RETURN s.SingerId AS SingerId) TABLESAMPLE BERNOULLI (10 PERCENT)`},
	{Label: "gql-surface/linear/tablesample-bernoulli", SQL: `GRAPH MusicGraph MATCH (s:Singers) TABLESAMPLE BERNOULLI (10 PERCENT) RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/linear/tablesample-reservoir", SQL: `GRAPH MusicGraph MATCH (s:Singers) TABLESAMPLE RESERVOIR (2 ROWS) RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/linear/tablesample-control", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id`},

	{Label: "gql-surface/factorized/quantified-left", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3} @{FACTORIZED_MODE=FACTORIZE_LEFT}(b:Singers) LET total_key = SUM(e.SingerId) RETURN b.SingerId AS dst_id, b.FirstName AS dst_name, total_key`},
	{Label: "gql-surface/factorized/quantified-control", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3}(b:Singers) LET total_key = SUM(e.SingerId) RETURN b.SingerId AS dst_id, b.FirstName AS dst_name, total_key`},
	{Label: "gql-surface/aggregate/horizontal-array-agg-ordered", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3}(b:Singers) LET titles = ARRAY_AGG(e.AlbumTitle ORDER BY e.AlbumTitle) RETURN a.SingerId AS src_id, b.SingerId AS dst_id, titles`},
	{Label: "gql-surface/aggregate/horizontal-array-agg-unordered-control", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3}(b:Singers) LET titles = ARRAY_AGG(e.AlbumTitle) RETURN a.SingerId AS src_id, b.SingerId AS dst_id, titles`},
	{Label: "gql-surface/aggregate/horizontal-count-distinct", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3}(b:Singers) LET unique_titles = COUNT(DISTINCT e.AlbumTitle) RETURN a.SingerId AS src_id, b.SingerId AS dst_id, unique_titles`},
	{Label: "gql-surface/aggregate/horizontal-count-control", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3}(b:Singers) LET title_count = COUNT(e.AlbumTitle) RETURN a.SingerId AS src_id, b.SingerId AS dst_id, title_count`},

	{Label: "gql-surface/match/inner-control", SQL: `GRAPH MusicGraph MATCH (s:Singers) MATCH (s)-[c:CollabWith]->(f:Singers) RETURN s.SingerId AS singer_id, f.SingerId AS friend_id`},
	{Label: "gql-surface/match/optional", SQL: `GRAPH MusicGraph MATCH (s:Singers) OPTIONAL MATCH (s)-[c:CollabWith]->(f:Singers) RETURN s.SingerId AS singer_id, f.SingerId AS friend_id`},
	{Label: "gql-surface/linear/next-two-stage-traversal", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[:CollabWith]->(frontier:Singers) RETURN frontier NEXT MATCH (frontier)-[:CollabWith]->(dest:Singers) RETURN frontier.SingerId AS frontier_id, dest.SingerId AS destination_id`},

	{Label: "gql-surface/unsupported/gql-row-number", SQL: `GRAPH MusicGraph MATCH (p:Singers) RETURN p.SingerId AS singer_id, ROW_NUMBER() OVER (ORDER BY p.SingerId) AS rn`},
	{Label: "gql-surface/unsupported/sql-is-first-control", SQL: `SELECT IS_FIRST(1) OVER (ORDER BY SingerId) FROM Singers`},
	{Label: "gql-surface/unsupported/pagerank-requires-export", SQL: `GRAPH MusicGraph CALL PageRank() YIELD node, score RETURN node.SingerId AS singer_id, score`},
	{Label: "gql-surface/unsupported/gql-native-qualify", SQL: `GRAPH MusicGraph MATCH (p:Singers) RETURN p.SingerId AS singer_id QUALIFY singer_id > 0`},
	{Label: "gql-surface/unsupported/sql-qualify-control", SQL: `SELECT SingerId FROM Singers QUALIFY SingerId > 0`},
	{Label: "gql-surface/unsupported/any-path-count", SQL: `GRAPH MusicGraph MATCH ANY 2 (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId, b.SingerId`},
	{Label: "gql-surface/unsupported/shortest-path-count", SQL: `GRAPH MusicGraph MATCH SHORTEST 2 (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId, b.SingerId`},
	{Label: "gql-surface/unsupported/all-shortest", SQL: `GRAPH MusicGraph MATCH ALL SHORTEST (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId, b.SingerId`},
	{Label: "gql-surface/unsupported/simple-path", SQL: `GRAPH MusicGraph MATCH SIMPLE PATH (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/unsupported/search-prefix-with-path-mode", SQL: `GRAPH MusicGraph MATCH ANY SHORTEST ACYCLIC PATH (a:Singers)-[:CollabWith]->{1, 3}(b:Singers) RETURN a.SingerId, b.SingerId`},
	{Label: "gql-surface/unsupported/tablesample-system", SQL: `GRAPH MusicGraph MATCH (s:Singers) TABLESAMPLE SYSTEM (10 PERCENT) RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/unsupported/tablesample-repeatable", SQL: `GRAPH MusicGraph MATCH (s:Singers) TABLESAMPLE BERNOULLI (10 PERCENT) REPEATABLE (42) RETURN s.SingerId AS singer_id`},
	{Label: "gql-surface/unsupported/malformed-label-or", SQL: `GRAPH LabelGraph MATCH (n:(Singer|)) RETURN ELEMENT_ID(n) AS element_id`},
	{Label: "gql-surface/unsupported/tablesample-with-weight", SQL: `GRAPH MusicGraph MATCH (s:Singers) TABLESAMPLE RESERVOIR (2 ROWS) WITH WEIGHT AS sample_weight RETURN s.SingerId AS singer_id, sample_weight`},
	{Label: "gql-surface/unsupported/unbounded-quantifier", SQL: `GRAPH MusicGraph MATCH ACYCLIC (a:Singers)-[:CollabWith]->+(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/unsupported/all-cheapest", SQL: `GRAPH MusicGraph MATCH ALL CHEAPEST (a:Singers)-[e:CollabWith COST 1]->{1,3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/unsupported/cheapest-path-count", SQL: `GRAPH MusicGraph MATCH CHEAPEST 2 (a:Singers)-[e:CollabWith COST 1]->{1,3}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-surface/unsupported/pagerank-call-per-requires-export", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->(b:Singers) CALL PER () PageRank() YIELD node AS ranked_node, score AS rank_score RETURN ranked_node.SingerId AS singer_id, rank_score`},
	{Label: "gql-surface/unsupported/optional-call-per", SQL: `GRAPH MusicGraph MATCH (s:Singers) OPTIONAL CALL PER () MissingGraphTVF() YIELD node RETURN 1 AS x`},
	{Label: "gql-surface/unsupported/final-graph-element", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s`},
	{Label: "gql-surface/unsupported/graph-table-final-element", SQL: `SELECT n FROM GRAPH_TABLE(MusicGraph MATCH (n:Singers) RETURN n)`},
	{Label: "gql-surface/unsupported/mixed-set-operation-kinds", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS id UNION ALL MATCH (t:Singers) RETURN t.SingerId AS id EXCEPT DISTINCT MATCH (u:Singers) RETURN u.SingerId AS id`},
	{Label: "gql-surface/unsupported/export-data-graph-shape", SQL: `EXPORT DATA OPTIONS (uri = "gs://unused-spanalyzer-plan-probe/pagerank/*.csv", format = "CSV") AS GRAPH MusicGraph CALL PageRank(node_labels => ["Singers"], edge_labels => ["CollabWith"]) YIELD node, score RETURN node.SingerId AS singer_id, score`},
}, gqlISFirstSurfaceQueries...)
