package main

// gqlHintSurfaceQueries retains graph-specific hint placements. Version
// boundaries and cross-query equality are enforced by the Omni integration
// test so --optimizer-version-matrix remains meaningful for every base case.
var gqlHintSurfaceQueries = []queryCase{
	{Label: "gql-hint/factorized/quantified-both", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3} @{FACTORIZED_MODE=FACTORIZE_BOTH}(b:Singers) LET total_key = SUM(e.SingerId) RETURN a.SingerId AS src_id, a.FirstName AS src_name, b.SingerId AS dst_id, b.FirstName AS dst_name, total_key`},
	{Label: "gql-hint/factorized/quantified-control", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->{1,3}(b:Singers) LET total_key = SUM(e.SingerId) RETURN a.SingerId AS src_id, a.FirstName AS src_name, b.SingerId AS dst_id, b.FirstName AS dst_name, total_key`},
	{Label: "gql-hint/factorized/nonlinear-both", SQL: `GRAPH MusicGraph MATCH (a:Singers {SingerId: 1})-[e1:CollabWith]->(b:Singers), @{FACTORIZED_MODE=FACTORIZE_BOTH} (a:Singers)-[e2:CollabWith]->(c:Singers), (a:Singers)-[e3:CollabWith]->(d:Singers) FILTER e1.AlbumTitle < "m" AND e2.AlbumTitle >= "m" AND e2.AlbumTitle < "t" AND e3.AlbumTitle >= "t" LET combined_title = CONCAT(e1.AlbumTitle, e2.AlbumTitle, e3.AlbumTitle) RETURN b.SingerId AS b_id, c.SingerId AS c_id, d.SingerId AS d_id, combined_title`},
	{Label: "gql-hint/factorized/nonlinear-control", SQL: `GRAPH MusicGraph MATCH (a:Singers {SingerId: 1})-[e1:CollabWith]->(b:Singers), (a:Singers)-[e2:CollabWith]->(c:Singers), (a:Singers)-[e3:CollabWith]->(d:Singers) FILTER e1.AlbumTitle < "m" AND e2.AlbumTitle >= "m" AND e2.AlbumTitle < "t" AND e3.AlbumTitle >= "t" LET combined_title = CONCAT(e1.AlbumTitle, e2.AlbumTitle, e3.AlbumTitle) RETURN b.SingerId AS b_id, c.SingerId AS c_id, d.SingerId AS d_id, combined_title`},

	{Label: "gql-hint/set-operation/direct-hint-unsupported", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id INTERSECT @{JOIN_METHOD=HASH_JOIN} DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-hint/set-operation/statement-hash", SQL: `@{JOIN_METHOD=HASH_JOIN} GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id INTERSECT DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-hint/set-operation/statement-merge", SQL: `@{JOIN_METHOD=MERGE_JOIN} GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id INTERSECT DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-hint/set-operation/statement-apply", SQL: `@{JOIN_METHOD=APPLY_JOIN} GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id INTERSECT DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-hint/set-operation/statement-push", SQL: `@{JOIN_METHOD=PUSH_BROADCAST_HASH_JOIN} GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->(b:Singers) RETURN b.SingerId AS id INTERSECT DISTINCT MATCH (p:Singers) FILTER p.SingerId > 0 RETURN p.SingerId AS id`},
	{Label: "gql-hint/set-operation/arm-mixed-hash-apply", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[:CollabWith]->@{JOIN_METHOD=HASH_JOIN}(b:Singers) RETURN b.SingerId AS id INTERSECT DISTINCT MATCH (p:Singers)-[:CollabWith]->@{JOIN_METHOD=APPLY_JOIN, BATCH_MODE=FALSE}(q:Singers) RETURN q.SingerId AS id`},

	{Label: "gql-hint/subquery/exists-hash-multi-pass-accepted-no-effect", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, EXISTS @{JOIN_METHOD=HASH_JOIN, HASH_JOIN_BUILD_SIDE=BUILD_LEFT, HASH_JOIN_EXECUTION=MULTI_PASS} { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f } AS has_friend`},
	{Label: "gql-hint/subquery/exists-hash-one-pass-accepted-no-effect", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, EXISTS @{JOIN_METHOD=HASH_JOIN, HASH_JOIN_BUILD_SIDE=BUILD_LEFT, HASH_JOIN_EXECUTION=ONE_PASS} { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f } AS has_friend`},
	{Label: "gql-hint/subquery/value-apply-batch-false-unsupported", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, VALUE @{JOIN_METHOD=APPLY_JOIN, BATCH_MODE=FALSE} { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f.SingerId ORDER BY f.SingerId LIMIT 1 } AS first_friend_id`},
	{Label: "gql-hint/subquery/value-apply-unsupported", SQL: `GRAPH MusicGraph MATCH (s:Singers) RETURN s.SingerId AS singer_id, VALUE @{JOIN_METHOD=APPLY_JOIN} { MATCH (x:Singers)-[:CollabWith]->(f:Singers) FILTER x = s RETURN f.SingerId ORDER BY f.SingerId LIMIT 1 } AS first_friend_id`},

	{Label: "gql-hint/element/node-force-base-table", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=_BASE_TABLE} p:Singers) RETURN p.SingerId AS singer_id, p.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName} p:Singers) RETURN p.SingerId AS singer_id, p.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index-scan-row", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, SCAN_METHOD=ROW} p:Singers) RETURN p.SingerId AS singer_id, p.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index-scan-batch", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, SCAN_METHOD=BATCH} p:Singers) RETURN p.SingerId AS singer_id, p.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index-scan-columnar", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, SCAN_METHOD=COLUMNAR} p:Singers) RETURN p.SingerId AS singer_id, p.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index-scan-no-columnar", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, SCAN_METHOD=NO_COLUMNAR} p:Singers) RETURN p.SingerId AS singer_id, p.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index-seekable-key-size-0", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, SEEKABLE_KEY_SIZE=0} p:Singers) FILTER p.FirstName = "Alice" AND p.LastName >= "M" RETURN p.SingerId AS singer_id`},
	{Label: "gql-hint/element/node-force-secondary-index-seekable-key-size-1", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, SEEKABLE_KEY_SIZE=1} p:Singers) FILTER p.FirstName = "Alice" AND p.LastName >= "M" RETURN p.SingerId AS singer_id`},
	{Label: "gql-hint/element/node-index-strategy-force-index-union", SQL: `GRAPH MusicGraph MATCH (@{INDEX_STRATEGY=FORCE_INDEX_UNION} s:Singers) FILTER s.FirstName = "Alice" OR s.LastName = "Smith" RETURN s.SingerId AS singer_id`},
	{Label: "gql-hint/element/node-index-strategy-control", SQL: `GRAPH MusicGraph MATCH (s:Singers) FILTER s.FirstName = "Alice" OR s.LastName = "Smith" RETURN s.SingerId AS singer_id`},
	{Label: "gql-hint/element/node-force-secondary-index-groupby-scan-true", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, GROUPBY_SCAN_OPTIMIZATION=TRUE} s:Singers) RETURN DISTINCT s.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index-groupby-scan-false", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName, GROUPBY_SCAN_OPTIMIZATION=FALSE} s:Singers) RETURN DISTINCT s.FirstName AS first_name`},
	{Label: "gql-hint/element/node-force-secondary-index-groupby-scan-control", SQL: `GRAPH MusicGraph MATCH (@{FORCE_INDEX=SingersByFirstLastName} s:Singers) RETURN DISTINCT s.FirstName AS first_name`},
	{Label: "gql-hint/graph-table/node-scan-row", SQL: `SELECT SingerId FROM GRAPH_TABLE(MusicGraph MATCH (@{SCAN_METHOD=ROW} p:Singers) RETURN p.SingerId AS SingerId)`},
	{Label: "gql-hint/graph-table/node-scan-batch", SQL: `SELECT SingerId FROM GRAPH_TABLE(MusicGraph MATCH (@{SCAN_METHOD=BATCH} p:Singers) RETURN p.SingerId AS SingerId)`},
	{Label: "gql-hint/element/edge-scan-row", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[@{SCAN_METHOD=ROW} e:CollabWith]->(f:Singers) RETURN s.SingerId AS singer_id, f.SingerId AS friend_id`},
	{Label: "gql-hint/element/edge-scan-batch", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[@{SCAN_METHOD=BATCH} e:CollabWith]->(f:Singers) RETURN s.SingerId AS singer_id, f.SingerId AS friend_id`},
	{Label: "gql-hint/element/traversal-merge", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[c:CollabWith]->@{JOIN_METHOD=MERGE_JOIN}(featured:Singers) RETURN s.SingerId AS singer_id, featured.SingerId AS featured_id`},
	{Label: "gql-hint/element/traversal-hash-build-left", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->@{JOIN_METHOD=HASH_JOIN, HASH_JOIN_BUILD_SIDE=BUILD_LEFT}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-hint/element/traversal-hash-build-right", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->@{JOIN_METHOD=HASH_JOIN, HASH_JOIN_BUILD_SIDE=BUILD_RIGHT}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-hint/element/traversal-apply-batch-true", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->@{JOIN_METHOD=APPLY_JOIN, BATCH_MODE=TRUE}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-hint/element/traversal-apply-batch-false", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->@{JOIN_METHOD=APPLY_JOIN, BATCH_MODE=FALSE}(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-hint/element/node-to-edge-hash-build-right", SQL: `GRAPH MusicGraph MATCH (a:Singers)@{JOIN_METHOD=HASH_JOIN, HASH_JOIN_BUILD_SIDE=BUILD_RIGHT}-[e:CollabWith]->(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-hint/element/node-to-edge-control", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e:CollabWith]->(b:Singers) RETURN a.SingerId AS src_id, b.SingerId AS dst_id`},
	{Label: "gql-hint/element/subpath-to-edge-apply-batch-false", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)) @{JOIN_METHOD=APPLY_JOIN, BATCH_MODE=FALSE} -[e2:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/element/subpath-to-edge-control", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)) -[e2:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/element/between-path-patterns-hash", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)), @{JOIN_METHOD=HASH_JOIN} ((b:Singers)-[e2:CollabWith]->(c:Singers)) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/element/between-path-patterns-control", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)), ((b:Singers)-[e2:CollabWith]->(c:Singers)) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	// These two placements are accepted and plan-visible on the pinned Omni
	// runtime even though the current Spanner graph-hint documentation says
	// that hints are not allowed between a subpath and node or two subpaths.
	{Label: "gql-hint/runtime-extension/subpath-to-node-hash", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)) @{JOIN_METHOD=HASH_JOIN} (c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/runtime-extension/subpath-to-node-control", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)) (c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/runtime-extension/subpath-to-subpath-hash", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)) @{JOIN_METHOD=HASH_JOIN} ((b:Singers)-[e2:CollabWith]->(c:Singers)) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/runtime-extension/subpath-to-subpath-control", SQL: `GRAPH MusicGraph MATCH ((a:Singers)-[e1:CollabWith]->(b:Singers)) ((b:Singers)-[e2:CollabWith]->(c:Singers)) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/match/second-merge", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e1:CollabWith]->(b:Singers) MATCH @{JOIN_METHOD=MERGE_JOIN} (b)-[e2:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/match/second-push", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e1:CollabWith]->(b:Singers) MATCH @{JOIN_METHOD=PUSH_BROADCAST_HASH_JOIN} (b)-[e2:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/match/second-control", SQL: `GRAPH MusicGraph MATCH (a:Singers)-[e1:CollabWith]->(b:Singers) MATCH (b)-[e2:CollabWith]->(c:Singers) RETURN a.SingerId AS src_id, c.SingerId AS dst_id`},
	{Label: "gql-hint/version/traversal-push", SQL: `GRAPH MusicGraph MATCH (s:Singers)-[c:CollabWith]->@{JOIN_METHOD=PUSH_BROADCAST_HASH_JOIN}(featured:Singers) RETURN s.SingerId AS singer_id, featured.SingerId AS featured_id`},
}
